---
extends: default

rules:
  brackets:
    # forbid: false
    # min-spaces-inside: 0
    max-spaces-inside: 1
    # min-spaces-inside-empty: -1
    max-spaces-inside-empty: 1
  commas:
    max-spaces-before: 1
    # min-spaces-after: 1
    # max-spaces-after: 1
  quoted-strings:
    required: false
  truthy:
    check-keys: false
...
