
name: 'Continuous Integration'
on:
  push:
    branches: [ master , ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  'trunk':
    name: 'Lint with Trunk.io'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Trunk Check
        uses: trunk-io/trunk-action@main
