name: 'Continuous Integration'
on:
  push:
    branches: [ master , ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  'trunk':
    name: 'Lint with Trunk.io'
    runs-on: ubuntu-latest
    permissions:
      checks: write # For trunk to post annotations
      contents: read # For repo checkout
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Trunk Check
        uses: trunk-io/trunk-action@main
        with:
          debug: true
      - if: failure()
        run: |
          set -vx
          ls -la "$(dirname "${TRUNK_PATH}")" || true
          ls -la "${TRUNK_PATH}" || true
          curl --verbose -fSL https://trunk.io/releases/trunk -o "${TRUNK_PATH}" || true
          ls -la "${TRUNK_PATH}" || true
          bash -vx "${TRUNK_PATH}" version
        
