---
name: 'Smoke test'
on:
  branch_protection_rule:
  check_run:
  check_suite:
  create:
  delete:
  deployment:
  deployment_status:
  discussion:
  discussion_comment:
  fork:
  gollum:
  issue_comment:
  issues:
  label:
  merge_group:
  milestone:
  page_build:
  project:
  project_card:
  project_column:
  public:
  pull_request:
  pull_request_review:
  pull_request_review_comment:
  pull_request_target:
  push:
  registry_package:
  release:
  repository_dispatch:
  schedule:
    - cron: '0 0 * * *'
  status:
  watch:
  workflow_call:
  workflow_run:
    workflows: [ 'Lint' ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  'test':
    name: 'Test some commands'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash --noprofile --norc -o errexit -o pipefail -o nounset -c "source ./core.sh ; set +o verbose +o xtrace ; source '{0}'"
    steps:
      - name: 'Checkout'
        uses: actions/checkout@main

      - name: 'Context'
        run: |
          set -x
          echo "$(context.eventName)"
          echo "$(context.sha)"
          echo "$(context.ref)"
          echo "$(context.workflow)"
          echo "$(context.action)"
          echo "$(context.actor)"
          echo "$(context.job)"
          echo "$(context.runAttempt)"
          echo "$(context.runNumber)"
          echo "$(context.runId)"
          echo "$(context.apiUrl)"
          echo "$(context.serverUrl)"
          echo "$(context.graphqlUrl)"
          echo "$(context.payload)"
          echo "$(context.payload ".sender")"
          echo "$(context.repo)"
          echo "$(context.issue)"
...
