---
name: 'Smoke test'
on:
  branch_protection_rule:
  check_run:
  check_suite:
  create:
  delete:
  deployment:
  deployment_status:
  discussion:
  discussion_comment:
  fork:
  gollum:
  issue_comment:
  issues:
  label:
  merge_group:
  milestone:
  page_build:
  project:
  project_card:
  project_column:
  public:
  pull_request:
  pull_request_review:
  pull_request_review_comment:
  pull_request_target:
  push:
  registry_package:
  release:
  repository_dispatch:
  schedule:
    - cron: '0 0 * * *'
  status:
  watch:
  workflow_call:
  workflow_run:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  'test':
    name: 'Test some commands'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash --noprofile --norc -o errexit -o pipefail -o nounset -c "source ${GITHUB_WORKSPACE}/core.sh ; set +o verbose +o xtrace ; source '{0}'"
    steps:
      - name: 'Checkout'
        uses: actions/checkout@main

      - name: 'Context'
        run: |
          set -x
          context.eventName
          context.sha
          context.ref
          context.workflow
          context.action
          context.actor
          context.job
          context.runAttempt
          context.runNumber
          context.runId
          context.apiUrl
          context.serverUrl
          context.graphqlUrl
          context.payload
          context.payload ".sender"
          context.repo
          context.issue
...
