---
name: 'Smoke test'
on:
  branch_protection_rule:
  check_run:
  check_suite:
  create:
  delete:
  deployment:
  deployment_status:
  discussion:
  discussion_comment:
  fork:
  gollum:
  issue_comment:
  issues:
  label:
  merge_group:
  milestone:
  page_build:
  project:
  project_card:
  project_column:
  public:
  pull_request:
  pull_request_review:
  pull_request_review_comment:
  pull_request_target:
  push:
  registry_package:
  release:
  repository_dispatch:
  schedule:
    - cron: '0 0 * * *'
  status:
  watch:
  workflow_call:
  workflow_run:
    workflows: [ 'Lint' ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  'test':
    name: 'Test some commands'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: >
          bash --noprofile --norc
          -o errexit -o pipefail -o nounset
          -c "source ${{github.workspace}}/core.sh ; set +o verbose +o xtrace ; source '{0}'"
    steps:
      - name: 'Checkout'
        uses: actions/checkout@main

      - name: 'Context'
        run: |
          pprint(){
            echo "$( printf '`%s` ' "${@}" )=> '$( "${@}" )'"
          }
          pprint context.eventName
          pprint context.sha
          pprint context.ref
          pprint context.workflow
          pprint context.action
          pprint context.actor
          pprint context.job
          pprint context.runAttempt
          pprint context.runNumber
          pprint context.runId
          pprint context.apiUrl
          pprint context.serverUrl
          pprint context.graphqlUrl
          echo "::group::context.payload =⌄⌄⌄⌄⌄⌄⌄⌄⌄⌄"
          context.payload | jq . --color-output | sed 's|^|  |'
          echo "::endgroup::"
          pprint context.payload ".sender.login"
          pprint context.repo
          pprint context.issue
...
